apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data0-myminio-pool-0-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: data0-myminio-pool-0-0